fix(ray): fix etrypoint module not found (#126)
Because

- `model.py` not in the user root dir and will cause
```
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/_private/utils.py", line 1194, in import_attr
    return getattr(module, attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'model' has no attribute 'entrypoint'
```

This commit

- move the model files back into user root
- update scope of model file size calculation